### ISSUE TITLE
Solve the problem of double definition of encodings in .gitattributes and zapp.yaml

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#125]
## Description of the enhancement requested

The _Z Open Editor_ extension provides for declaring file encodings in the `zapp.yaml` document, through mappings, and this for the sole benefit of RSE:

```
profiles:
  - name: RSE-Mappings
    type: rseapi
    settings:
      mappings:
        - resource: "**.SAMPLE.COB**"
          extension: cbl
          transfer: text
          encoding: IBM-037
          memberMappings:
            - extension: dat
              transfer: binary
              resource: "*DAT"
        - resource: "**PLI*"
          extension: pl1
          transfer: text
          encoding: IBM-037
      default.encoding: IBM-037
```

In my opinion, this is the source of several problems:

- there is no reason to privilege access by RSE to the detriment of access by z/OSMF, or even possibly other agents access (FTP for example, or third-party services on wich we are investigating).

- the declarations made in `zapp.yaml` are redundant, even conflicting with the declarations made in `.gitignore` (when using Git repositories for the storage of sources which must be the most common case), for the using _Git for z/OS_: `zos-working-tree-encoding` declarations, (it seems to me that _Git for z/OS_ is required for using _IBM Dependency Base Builder_):

```
* .cpy zos-working-tree-encoding=ibm-1047 git-encoding=utf-8
* .cbl zos-working-tree-encoding=ibm-1047 git-encoding=utf-8
* .jcl zos-working-tree-encoding=ibm-1047 git-encoding=utf-8
* .bms zos-working-tree-encoding=ibm-1047 git-encoding=utf-8
* .pli zos-working-tree-encoding=ibm-1047 git-encoding=utf-8
* .inc zos-working-tree-encoding=ibm-1047 git-encoding=utf-8
* .asm zos-working-tree-encoding=ibm-1047 git-encoding=utf-8
* .mfs zos-working-tree-encoding=ibm-1047 git-encoding=utf-8
* .bnd zos-working-tree-encoding=ibm-1047 git-encoding=utf-8
* .lnk zos-working-tree-encoding=ibm-1047 git-encoding=utf-8
* .rex zos-working-tree-encoding=ibm-1047 git-encoding=utf-8
* .txt zos-working-tree-encoding=ibm-1047 git-encoding=utf-8
* .groovy zos-working-tree-encoding=ibm-1047 git-encoding=utf-8
* .sh zos-working-tree-encoding=ibm-1047 git-encoding=utf-8
* .properties zos-working-tree-encoding=ibm-1047 git-encoding=utf-8
* .rexx zos-working-tree-encoding=ibm-1047 git-encoding=utf-8
* .config zos-working-tree-encoding=ibm-1047 git-encoding=utf-8
```

_Z Open Editor_ should therefore take into account the declarations made at the `.gitignore` level in addition to the declarations made in `zapp.yaml`, according to a priority to be defined,(in my opinion `.gitattributes` should take precedence over `zapp.yaml`).

_Z Open Editor_ should also use the encoding declarations for all agents access, and in particular the z/OSMF agent access, systematically passing as a parameter the appropriate encoding for the transfer of a file or a PDS member, (addition of the -ec option, or equivalent, on transfer requests).
