### ISSUE TITLE
All languages - Relative path to current edited file for local syslib and location in settings.json / zapp.yaml

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#163]
## Description of the enhancement requested

The local search for COPYBOOK / INCLUDE by Z Open Editor allows the use of relative paths, without specifying what they are relative to.

We want to be able to indicate that the search should be relative to the location of the file being edited, and Z Open Editor doesn't seem to work that way for relative paths.

Consider the following folder tree:

```
└───src
    ├───PARENT1
    │   ├───COBOL
    │   └───COPYCOB
    ├───PARENT2
    │   ├───COBOL
    │   └───COPYCOB
    └───PARENT3
        ├───COBOL
        └───COPYCOB
```

We want the local COPYBOOK search for a COBOL source file edited from a `COBOL` folder to be done in the `COPYCOB` folder located at the same level as the `COBOL` folder.

In the `zapp.yaml` file we made the following declaration:

```
property-groups:
  - name: cobol-local
    language: cobol
    type: local
    syslib:
      - ../COPYCOB/**
```
 
However, this does not give the expected result. he COPYBOOK is not found. 

One solution would be to support VS Code environment variables, (https://code.visualstudio.com/docs/editor/variables-reference), but this would create a dependency on VS Code.

```
property-groups:
  - name: cobol-local
    language: cobol
    type: local
    compilerOptions: "APOST,CODEPAGE(1147)"
    syslib:
      - ${fileDirname}/../COPYCOB/**
```
