### ISSUE TITLE
Configure Paths for include file searching

### ISSUE THREAD

**Issue by BJostmeyer** [IBM/zopeneditor-about#254]
Hi,
I am using the editor especially for PL1 and REXX files. In our source project We do have a directory structure in which files that contain functions and thus are included with a statement eg:
....
/*%INCLUDE REXMAC1 */
...

are not found by the editor since this file is in another directory.

Instead I see Warning like:

The REXX language server requested the include file "REXMAC1 ", which was not found. enforceCaseSensitiveIncludeFileNames was set to false. Check your Zowe CLI profile and property group settings and if you have not already done so, switch to the "DEBUG" log level for more information.

My question is: is there a way to configure mutliple directories (relative location) to do this?

Thanks.

**Comment by FALLAI-Denis** [comment]
Hi,

Rexx include file must have a `.rex` or `.rexx` extension.

See [Datasets setting missing for Rexx highlighting](https://github.com/IBM/zopeneditor-about/issues/172#issuecomment-1159395724)

VS Code should be opened in "folder" mode, (blue statusbar), not "file" mode (purple statusbar).

If the rexx include is in the Workspace, a path expressed as `from/**/folder/**` should search in all folders under `from` that have a subfolder named `folder`.

With the following cases:
- `**/folder`: all lower level folders named `folder` in the workspace
- `from/**/folder`: all lower level folders named `folder` below the root folder `from`

I don't think you can reference includes that aren't in the workspace.

Extract from my configuration (zapp.yaml):
```
property-groups:
  - name: cobol-local
    language: cobol
    type: local
    syslib:
      - "**/COPYCOB"         <-- any folder named COPYBOOK
      - ".imports"           <-- the root folder .imports
    [...]
  - name: hlasm-local
    language: hlasm
    type: local
    syslib:
      - "src/**/COPYASM"     <-- any folder named COPYASM descendant of root src folder
      - "src/**/MACASM"      <-- any folder named MACASM descendant of root src folder
      - ".imports"           <-- the root folder .imports
    [...]
```
