### ISSUE TITLE
IBM User Build - ${buildFile.workspaceDir} return a relative path including also Workspace name (not relative to Workspace)

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#294]
## Development environment used

- Z Open Editor version: 3.0.0
- Editor Platform
  - [X] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: 1.72.2
- Operating System: Windows 10
- Java Version: 11
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached: yes

[setup and run IBM user build.txt](https://github.com/IBM/zopeneditor-about/files/10114630/setup.and.run.IBM.user.build.txt)

## Problem Description

Detailed steps for reproducing the problem:

1. Define the dbb profile as this:

```
profiles:
  - name: dbb-userbuild
    type: dbb
    settings:
      application: CEAB3.MVP2
      command: "$DBB_HOME/bin/groovyz"
      buildScriptPath: "/var/DBB/PROD/SCRIPTS/buildBPCE.groovy"
      buildScriptArgs:
        - "--userBuild"
        - "--workspace ${zopeneditor.userbuild.userSettings.dbbWorkspace}"
        - "--application ${application}"
        - "--hlq ${zopeneditor.userbuild.userSettings.dbbHlq}.${application}"
        - "--outDir ${zopeneditor.userbuild.userSettings.dbbLogDir}"
        - "--dependencyFile ${dependencyFile}"
      additionalDependencies:
        - application-conf
        - .build
        - "${buildFile.workspaceDir}\\${buildFile}.build"     <== problem here
      logFilePatterns:
        - "${buildFile.basename}.log"
        - "BuildReport.*"
```

2. create a `src\COBOL\S9TL1A.cbl` and a `src\COBOL\S9TL1A.cbl.build`

![image](https://user-images.githubusercontent.com/63861965/204574165-34418a70-d922-4342-be52-e03f3b574f87.png)

4. run "setup for IBM User Build" from `src\COBOL\S9TL1A.cbl`

`src\COBOL\S9TL1A.cbl` is relative to the Workspace.

### Observed behavior

```
Identified the local root workspace path as c:\Trv\DepotsGIT\ceab3-environn-outinfr-central-mvp2
Running setup to build c:\Trv\DepotsGIT\ceab3-environn-outinfr-central-mvp2\src\COBOL\S9TL1A.cbl program.
[...]
Uploading additional dependencies matched inside workspace of the build file ...
Matching files for application-conf 
c:/Trv/DepotsGIT/ceab3-environn-outinfr-central-mvp2/application-conf
Matching files for .build 
c:/Trv/DepotsGIT/ceab3-environn-outinfr-central-mvp2/.build
Matching files for ceab3-environn-outinfr-central-mvp2\src\COBOL\S9TL1A.cbl.build 
No matched files found
```
The `${buildFile.workspaceDir}` variable does not return the path relative to the Workspace folder, but returns a path including the name of the Workspace folder.

`${buildFile.workspaceDir}\\${buildFile}.build` is translated as `ceab3-environn-outinfr-central-mvp2\src\COBOL\S9TL1A.cbl.build`.
`ceab3-environn-outinfr-central-mvp2` is the name and folder of the Workspace itself.

This is not consistent with the path to the file to build relative to the Workspace.

This is also not in agreement with the documentation: section _Substitution variables_ of https://www.ibm.com/docs/en/cloud-paks/z-modernization-stack/2022.4?topic=code-setting-up-user-build:
![image](https://user-images.githubusercontent.com/63861965/204573261-9b998831-4712-4a67-bd18-90c3b99c2771.png)

As-is not usable in IBM User Build setup for a Git repository opened in VS Code.

### Expected behavior

Expected translation for `${buildFile.workspaceDir}\\${buildFile}.build` from  `src\COBOL\S9TL1A.cbl` is `src\COBOL\S9TL1A.cbl.build` or to a full path as `c:\Trv\DepotsGIT\ceab3-environn-outinfr-central-mvp2\src\COBOL\S9TL1A.cbl`.

### Workaround

```
profiles:
  - name: dbb-userbuild
    type: dbb
    settings:
      application: CEAB3.MVP2
      command: "$DBB_HOME/bin/groovyz"
      buildScriptPath: "/var/DBB/PROD/SCRIPTS/buildBPCE.groovy"
      buildScriptArgs:
        - "--userBuild"
        - "--workspace ${zopeneditor.userbuild.userSettings.dbbWorkspace}"
        - "--application ${application}"
        - "--hlq ${zopeneditor.userbuild.userSettings.dbbHlq}.${application}"
        - "--outDir ${zopeneditor.userbuild.userSettings.dbbLogDir}"
        - "--dependencyFile ${dependencyFile}"
      additionalDependencies:
        - application-conf
        - .build
        - "src\\**\\${buildFile}.build"     <== workaround
      logFilePatterns:
        - "${buildFile.basename}.log"
        - "BuildReport.*"
```

```
Matching files for src\**\S9TL1A.cbl.build 
c:/Trv/DepotsGIT/ceab3-environn-outinfr-central-mvp2/src/COBOL/S9TL1A.cbl.build
```
