### ISSUE TITLE
IBM User Build - Cannot download log files from logs sub-folders

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#296]
## Development environment used

- Z Open Editor version: 3.0.0
- Editor Platform
  - [X] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: 1.72.2
- Operating System: Windows 10
- Java Version: 11
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html) how to get them): yes/no

## Problem Description

ZOE seems to have trouble identifying log files to download after a user build.

---

If we don't specify a filter with the logFilePatterns parameters, it downloads all the files of all the builds it finds, and ends up with an error:

```
profiles:
  - name: dbb-userbuild
    type: dbb
    settings:
      application: CEAB3.MVP2
      command: "$DBB_HOME/bin/groovyz"
      buildScriptPath: "/var/DBB/PROD/SCRIPTS/buildBPCE.groovy"
      buildScriptArgs:
        - "--userBuild"
        - "--workspace ${zopeneditor.userbuild.userSettings.dbbWorkspace}"
        - "--application ${application}"
        - "--hlq ${zopeneditor.userbuild.userSettings.dbbHlq}.${application}"
        - "--outDir ${zopeneditor.userbuild.userSettings.dbbLogDir}"                 <== log root folder
      additionalDependencies:
        - application-conf
        - .build
        - "src\\**\\${buildFile}.build"
```

```
Running User Build...
Identified the local root workspace path as c:\Trv\DepotsGIT\ceab3-environn-outinfr-central-mvp2
---------------------
Checking dbb profile settings defined in your repository's zapp.yaml or zapp.json
User setting dbbDefaultZappProfile: **dbb-userbuild**
Will read settings from ZAPP profile called dbb-userbuild defined in User Settings
    application: CEAB3.MVP2
    command: $DBB_HOME/bin/groovyz
    buildScriptArgs: --userBuild,--workspace /u/J070188/dbb,--application CEAB3.MVP2,--hlq J070188.DBB.CEAB3.MVP2,--outDir /u/J070188/dbb/logs
    buildScriptPath: /var/DBB/PROD/SCRIPTS/buildBPCE.groovy
    additionalDependencies: application-conf,.build,src\**\S9TL1A.cbl.build
    logFilePatterns: **Optional setting is missing**
---------------------
Checking user settings...
User settings should be defined in your VS Code or Theia Settings under zopeneditor.userbuild.userSettings
    dbbWorkspace: /u/J070188/dbb
    dbbHlq: J070188.DBB
    dbbLogDir: /u/J070188/dbb/logs
    dbbDefaultZappProfile: dbb-userbuild
    localLogDir: .reports
[...]
-------------------------------------------------------------------------------------------------------------------------
** Writing build report data to /u/J070188/dbb/logs/build.20221129.191008.010/BuildReport.json
** Writing build report to /u/J070188/dbb/logs/build.20221129.191008.010/BuildReport.html
-------------------------------------------------------------------------------------------------------------------------
** Build ended at Tue Nov 29 19:10:16 CET 2022
** Build State : CLEAN
** Total files in build list : 1
** Total build time  : 7.956 seconds
-------------------------------------------------------------------------------------------------------------------------
** Build finished
$ exit $?
Looking for user build logs in "/u/J070188/dbb/logs".       <== given value on --outDir parameter
Downloading logs to c:\Trv\DepotsGIT\ceab3-environn-outinfr-central-mvp2\.reports
Downloading log file /u/J070188/dbb/logs/.userbuilddependencies. Binary: false
Downloading log file /u/J070188/dbb/logs/build.20221129.162418.024. Binary: false
Downloading log file /u/J070188/dbb/logs/build.20221129.170139.001. Binary: false
Downloading log file /u/J070188/dbb/logs/build.20221129.171827.018. Binary: false
Downloading log file /u/J070188/dbb/logs/build.20221129.183526.035. Binary: false
Downloading log file /u/J070188/dbb/logs/build.20221129.184044.040. Binary: false
Downloading log file /u/J070188/dbb/logs/build.20221129.185218.052. Binary: false
Downloading log file /u/J070188/dbb/logs/build.20221129.191008.010. Binary: false   <== only this folder in concerned by current build
Error: Failed to download logs: Error: z/OSMF REST API Error:       <== unidentified error
Rest API failure with HTTP(S) status 500
category: 6
rc:       8
reason:   92078512
message:  file lock via fcntl() failed
details: 
  - EDC5121I Invalid argument. (errno2=0x055501B0)
```

`/u/J070188/dbb/logs/build.<date>.<time>.<mmm>` are folders... ZOE try to download files...

---

Specifying a filter with the File Patterns log parameters does not download any logs:

```
profiles:
  - name: dbb-userbuild
    type: dbb
    settings:
      application: CEAB3.MVP2
      command: "$DBB_HOME/bin/groovyz"
      buildScriptPath: "/var/DBB/PROD/SCRIPTS/buildBPCE.groovy"
      buildScriptArgs:
        - "--userBuild"
        - "--workspace ${zopeneditor.userbuild.userSettings.dbbWorkspace}"
        - "--application ${application}"
        - "--hlq ${zopeneditor.userbuild.userSettings.dbbHlq}.${application}"
        - "--outDir ${zopeneditor.userbuild.userSettings.dbbLogDir}"
      additionalDependencies:
        - application-conf
        - .build
        - "src\\**\\${buildFile}.build"
      logFilePatterns:
        - "${buildFile.basename}*.log"
        - "BuildReport.*"
```

```
Running User Build...
Identified the local root workspace path as c:\Trv\DepotsGIT\ceab3-environn-outinfr-central-mvp2
---------------------
Checking dbb profile settings defined in your repository's zapp.yaml or zapp.json
User setting dbbDefaultZappProfile: **dbb-userbuild**
Will read settings from ZAPP profile called dbb-userbuild defined in User Settings
    application: CEAB3.MVP2
    command: $DBB_HOME/bin/groovyz
    buildScriptArgs: --userBuild,--workspace /u/J070188/dbb,--application CEAB3.MVP2,--hlq J070188.DBB.CEAB3.MVP2,--outDir /u/J070188/dbb/logs
    buildScriptPath: /var/DBB/PROD/SCRIPTS/buildBPCE.groovy
    additionalDependencies: application-conf,.build,src\**\S9TL1A.cbl.build
    logFilePatterns: S9TL1A*.log,BuildReport.*
---------------------
Checking user settings...
User settings should be defined in your VS Code or Theia Settings under zopeneditor.userbuild.userSettings
    dbbWorkspace: /u/J070188/dbb
    dbbHlq: J070188.DBB
    dbbLogDir: /u/J070188/dbb/logs
    dbbDefaultZappProfile: dbb-userbuild
    localLogDir: .reports
[...]
** Writing build report data to /u/J070188/dbb/logs/build.20221129.192630.026/BuildReport.json
** Writing build report to /u/J070188/dbb/logs/build.20221129.192630.026/BuildReport.html
-------------------------------------------------------------------------------------------------------------------------
** Build ended at Tue Nov 29 19:26:36 CET 2022
** Build State : CLEAN
** Total files in build list : 1
** Total build time  : 6.417 seconds
-------------------------------------------------------------------------------------------------------------------------
** Build finished
$ exit $?
Looking for user build logs in "/u/J070188/dbb/logs".
Will download logs matching the following patterns: S9TL1A*.log,BuildReport.*
Downloading logs to c:\Trv\DepotsGIT\ceab3-environn-outinfr-central-mvp2\.reports
Successfully finished downloading of 0 log files to c:\Trv\DepotsGIT\ceab3-environn-outinfr-central-mvp2\.reports.   <== 0 log found
```

List from ssh session:
```
J070188:/u/J070188/dbb/logs: >find . -name S9TL1A* -o -name BuildReport*
./build.20221129.162418.024/BuildReport.json
./build.20221129.162418.024/BuildReport.html
./build.20221129.185218.052/logs/SIRIS/S9TL1A.log
./build.20221129.185218.052/logs/SIRIS/S9TL1A.lked.log
./build.20221129.185218.052/BuildReport.json
./build.20221129.185218.052/BuildReport.html
./build.20221129.191008.010/logs/SIRIS/S9TL1A.log
./build.20221129.191008.010/logs/SIRIS/S9TL1A.lked.log
./build.20221129.191008.010/BuildReport.json
./build.20221129.191008.010/BuildReport.html
./build.20221129.192630.026/logs/SIRIS/S9TL1A.log            <== last build run
./build.20221129.192630.026/logs/SIRIS/S9TL1A.lked.log    <== last build run
./build.20221129.192630.026/BuildReport.json                     <== last build run
./build.20221129.192630.026/BuildReport.html                    <== last build run
```
---

```
profiles:
  - name: dbb-userbuild
    type: dbb
    settings:
      application: CEAB3.MVP2
      command: "$DBB_HOME/bin/groovyz"
      buildScriptPath: "/var/DBB/PROD/SCRIPTS/buildBPCE.groovy"
      buildScriptArgs:
        - "--userBuild"
        - "--workspace ${zopeneditor.userbuild.userSettings.dbbWorkspace}"
        - "--application ${application}"
        - "--hlq ${zopeneditor.userbuild.userSettings.dbbHlq}.${application}"
        - "--outDir ${zopeneditor.userbuild.userSettings.dbbLogDir}"
      additionalDependencies:
        - application-conf
        - .build
        - "src\\**\\${buildFile}.build"
      logFilePatterns:
        - "${zopeneditor.userbuild.userSettings.dbbWorkspace}/**/${buildFile.basename}*.log"
        - "${zopeneditor.userbuild.userSettings.dbbWorkspace}/**/BuildReport.*"
```

```
** Writing build report data to /u/J070188/dbb/logs/build.20221129.201336.013/BuildReport.json
** Writing build report to /u/J070188/dbb/logs/build.20221129.201336.013/BuildReport.html
-------------------------------------------------------------------------------------------------------------------------
** Build ended at Tue Nov 29 20:13:42 CET 2022
** Build State : CLEAN
** Total files in build list : 1
** Total build time  : 6.545 seconds
-------------------------------------------------------------------------------------------------------------------------
** Build finished
$ exit $?
Looking for user build logs in "/u/J070188/dbb/logs".
Will download logs matching the following patterns: /u/J070188/dbb/**/S9TL1A*.log,/u/J070188/dbb/**/BuildReport.*
Downloading logs to c:\Trv\DepotsGIT\ceab3-environn-outinfr-central-mvp2\.reports
Successfully finished downloading of 0 log files to c:\Trv\DepotsGIT\ceab3-environn-outinfr-central-mvp2\.reports.   <== 0 log found
```
