### ISSUE TITLE
IBM User Build - Upload additional files at build run time

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#297]
## Description of the enhancement requested

IBM User Build allows uploading files to DBB workspace during `Run setup IBM User Build` using the `additionalDependencies` parameter.

We would also like to be able to upload additional files in DBB workspace during the `Run IBM User Build (with full upload)`.

It happens that files are linked to the file to build and are subject to modifications and that if one of the linked files is modified it must be uploaded to DBB workspace at the same time as the file to build.
This is the case for our `program.cbl.build` files which are associated with `program.cbl` files: one does not go without the other, and during a build of a `program.cbl` the file `program.cbl.build` must also be present in the DBB workspace.

Today we solved the problem by declaring the file `program.cbl.build` in the `additionalDependencies` parameter as `${buildFile}.build`, but in this case the file `program.cbl.build` is only uploaded during the `Run setup for IBM Build`, this which obliges to redo the setup each time the `program.cbl.build` file is modified, whereas it is a dependency on the `program.cbl` file (which ZOE cannot know because only the `build.groovy` script can resolve this dependency).

A solution would consist in uploading the files at each `Run IBM User Build` as soon as they refer to the file to be built, i.e. all the files present in `additionalDependencies` and which use the variable `${buildFile}` or one of its variants would be uploaded during a `Run IBM User Build`.

```
profiles:
  - name: dbb-userbuild
    type: dbb
    settings:
      application: CEAB3.MVP2
      command: "$DBB_HOME/bin/groovyz"
      buildScriptPath: "/var/DBB/PROD/SCRIPTS/buildBPCE.groovy"
      buildScriptArgs:
        - "--userBuild"
        - "--workspace ${zopeneditor.userbuild.userSettings.dbbWorkspace}"
        - "--application ${application}"
        - "--hlq ${zopeneditor.userbuild.userSettings.dbbHlq}.${application}"
        - "--outDir ${zopeneditor.userbuild.userSettings.dbbLogDir}"
      additionalDependencies:
        - application-conf                <== directory to upload only on Run setup for IBM User Build (no reference to ${buildFile})
        - .build                          <== directory to upload only on Run setup for IBM User Build (no reference to ${buildFile})
        - "src\\**\\${buildFile}.build"   <== file to upload on each Run IBM User Build (reference to ${buildFile})
      logFilePatterns:
        - "${buildFile.basename}*.log"
        - "BuildReport.*"
```
