### ISSUE TITLE
Latch Contention Issues and Dead TSO Address Spaces

### ISSUE THREAD

**Issue by savaresejt** [IBM/zopeneditor-about#445]
## Development environment used

- Z Open Editor version:
- Editor Platform
  - [x ] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version:
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3):
- Java Version (when using VS Code or Theia, execute `java -version` and paste the details here):
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version: v2.15.0
  - Node.js version: v18.20.4
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html) how to get them): yes/no

## Problem Description

Detailed steps for reproducing the problem:

1. First step

### Observed behavior
User reported having issues saving datasets with zowe explorer. We saw in the log thousands of error messages trying to locate datasets in ++include and copybooks. We observed ~13,000 dead address spaces from the tso user. This has happened 3 times in the last month.

OUTPUT FROM D GRS,C,L
```
RESPONSE=SYSELMD                                                       
 ISG343I 08.08.35 GRS STATUS 871                                       
 LATCH SET NAME:  SYS.BPX.AP00.PRTB1.PPRA.LSN                          
 CREATOR JOBNAME: OMVS      CREATOR ASID: 0010                         
   LATCH NUMBER:  1                                                    
     REQUESTOR  ASID  EXC/SHR    OWN/WAIT  WORKUNIT  TCB  ELAPSED TIME 
     USER1      0027  EXCLUSIVE  OWN       00AE41B0   Y   07:04:13.452 
     BPXOINIT   0041  EXCLUSIVE  WAIT      00AFAAE8   Y   07:04:13.450 
     USER1      0027  EXCLUSIVE  WAIT      00AE4800   Y   07:04:13.363 
     USER1      00E9  EXCLUSIVE  WAIT      00AE4800   Y   06:57:38.356 
     USER1      00AB  EXCLUSIVE  WAIT      00AE4800   Y   06:57:36.971 
     SSHD3      00F0  EXCLUSIVE  WAIT      00AD9DC8   Y   01:42:27.413 
     USER3      00F5  EXCLUSIVE  WAIT      00AFB2F8   Y   00:30:39.263 
     PORTMAP    0098  EXCLUSIVE  WAIT      00AF9040   Y   00:03:46.903 
   LATCH NUMBER:  47                                                   
     REQUESTOR  ASID  EXC/SHR    OWN/WAIT  WORKUNIT  TCB  ELAPSED TIME 
     USER1      00AA  EXCLUSIVE  OWN       00AE41B0   Y   16:42:25.036 
     USER1      00AA  EXCLUSIVE  WAIT      00AE4800   Y   16:27:14.359 
   LATCH NUMBER:  125                                                  
     REQUESTOR  ASID  EXC/SHR    OWN/WAIT  WORKUNIT  TCB  ELAPSED TIME 
     USER1      0099  EXCLUSIVE  OWN       00AE41B0   Y   15:40:55.436 
     USER1      0099  EXCLUSIVE  WAIT      00AE4800   Y   15:25:55.379 
 LATCH NUMBER:  260                                                    
   REQUESTOR  ASID  EXC/SHR    OWN/WAIT  WORKUNIT  TCB  ELAPSED TIME   
   USER3      00F5  EXCLUSIVE  OWN       00AFB2F8   Y   00:30:39.263   
   RSED3      0051  EXCLUSIVE  WAIT      00AC80A0   Y   00:30:36.665   
   RSED3      0051  EXCLUSIVE  WAIT      00AC1E88   Y   00:27:39.311   
 LATCH NUMBER:  1505                                                   
   REQUESTOR  ASID  EXC/SHR    OWN/WAIT  WORKUNIT  TCB  ELAPSED TIME   
   USER2      00D5  EXCLUSIVE  OWN       00AE41B0   Y   -over 24 hrs   
   USER2      00D5  EXCLUSIVE  WAIT      00AE4800   Y   -over 24 hrs   
 LATCH NUMBER:  1654                                                   
   REQUESTOR  ASID  EXC/SHR    OWN/WAIT  WORKUNIT  TCB  ELAPSED TIME   
   SSHD3      00F0  EXCLUSIVE  OWN       00AD9DC8   Y   01:42:27.413   
   SSHD4      0066  EXCLUSIVE  WAIT      00AFB2F8   Y   01:40:26.298   
   SSHD5      0121  EXCLUSIVE  WAIT      00AFB2F8   Y   00:17:57.800   	 
```
   
These commands recovered us

```
FORCE U=USER1,A=00AA,TCB=AE4800 
FORCE U=USER1,A=0099,TCB=AE4800
FORCE U=USER1,A=0099,TCB=AE4800
FORCE U=USER1,A=0099,TCB=AE4800
FORCE U=USER2,A=00d5,TCB=AE4800
```
### Expected behavior
We would still like to figure out the root cause here, this could cause issues if we move zopen editor up to production if we're getting system latches.

The zapp file users are using is:
```
name: Generated ZAPP document
description: >-
  Configuration file that controls where z-open editor will search for 
  COBOL copybooks so that they can be traced through the code by hovering
  Documentation:
  https://ibm.github.io/zopeneditor-about/Docs/setting_propertygroup.html
author: IBM Z Open Editor
propertyGroups:
  - name: search-all
    libraries:
      - name: syslib
        type: mvs
        locations:
          - XXX.DEV.COPYLIB
          - XXX.D.COPYLIB
          - XXX.S.COPYLIB
          - XXX.P.COPYLIB
          - XXX.D.DCLGEN          
          - XXX.S.DCLGEN           
          - XXX.P.DCLGEN     
          - XXX.P.DCLGEN
          - XXX.D.MAPLIB
          - XXX.S.MAPLIB
          - XXX.P.MAPLIB   
          - CICS.V6R1.CPSM.SEYUCOB     
          - CICS.V6R1.SDFHCOB
          - DB2.CADB2.V20R0M0.CDBACOBI
          - YYY.RAI.CRAICOBI
          - XXX.DEV.SOURCE
          - XXX.D.SOURCE 
          - XXX.S.SOURCE
          - XXX.P.SOURCE 
```
-
