### ISSUE TITLE
Reorganization of the design of property groups

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/zopeneditor-about#99]
## Description of the enhancement requested

Originally, property groups were only used to find COPYBOOKs / INCLUDEs to display them in the editor.

Subsequently, information on build options has been introduced, which is problematic as expressed in our other requests (# 97, # 98).

Due to the multiplication of informations managed in property groups, it is necessary to multiply groups.

The current shema separates the "local" and "mvs" declarations, which forces all other properties to be repeated identically in separate groups.

It might have been better to combine the "local" and "mvs" declarations in the same group sharing the same other properties.

The organization of a property-groups could approach this proposal (zapp.yaml format):
```
property-groups:
  - name: property-group-name
    language: cobol
    scope:
      - programs:
        - "path-and-mask-filter-1"
        - "path-and-mask-filter-2"
      - branches:
        - "name-mask-filter-1"
        - "name-mask-filter-2"
    compileOptions: option1, option2
    - type: local
      syslib:
      - "** / COPYBOOK"
      - "** / INCLUDES"
    - type: mvs
      syslib:
      - "HLQ1.SYSLIB.COBCOPY"
      - "HLQ2.SYSLIB.COBCOPY"
      libraries:
       - name: MYFILE
         locations:
         - "HLQ1.MYFILE.COPY"
         - "HLQ2.MYFILE.COPY"

```
New and modified properties:
* scope: property group selection mechanism for a set of programs and / or set of Git branches,
* programs: array of selection filters based on the name and location of the programs in the Workspace
* branches: array of selection filters based on Git branch name
* type: becomes an array
* syslib: becomes a sub-property of the type
* libraires: becomes a sub-property of the type
